version: 2

project_name: proxyrotator

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: proxyrotator
    main: .
    binary: proxyrotator
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/romeomihailus/proxyrotator/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: proxyrotator
    ids:
      - proxyrotator
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "🚀 Features"
      regexp: "^feat"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^fix"
      order: 1
    - title: "⚡ Performance"
      regexp: "^perf"
      order: 2
    - title: "🔧 Maintenance"
      order: 999

release:
  github:
    owner: romeomihailus
    name: proxyrotator
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto
